spring:
  application:
    name: ecommercemicroservice

  datasource:
    url: jdbc:mysql://localhost/dbCheckout
    username: "user_database"
    password: "pass_database"

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrapServers: 127.0.0.1:9092
    acksConfig: all
    retriesConfig: 10
    schemaRegistryUrl: http://127.0.0.1:8081
